baseurl = "https://www.bendb.com/"
languageCode = "en-us"
title = "bendb"
author = "Ben Bader"
theme = "cocoa"

layoutdir = "layouts"
publishdir = "public-blog"
pygmentscodefences = true
pygmentsstyle = "bw"
pluralizelisttitles = false

copyright = "&copy; 2020.  All rights reserved."
canonifyurls = true
builddrafts = false
contentdir = "content"
googleAnalytics = "UA-47968134-1"

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
  author = "Ben Bader"
  cachebuster = true
  dateform = "Jan 2, 2006"
  dateformfull = "Mon Jan 2 2006 15:04:05 PST"
  description = "Just Android stuff"
  email = "ben@bendb.com"
  github = "benjamin-bader"
  mastodon = "https://mastodon.online/@bendb"
  highlightjs = false
  lang = "en"
  linkedin = "bendb"
  twitter = "pianoben"
  selfIntro = ""
  disablefancyfonts = false
  logofile = "img/profile.jpg"
