name        = "Cocoa"
license     = "MIT"
licenselink = "https://todo"
description = "My Theme"
homepage    = "https://github.com/benjamin-bader"
tags        = ["blog"]
features    = ["blog", "responsive", "404", "icons", "metadata"]
min_version = 0.18

[author]
name      = "Ben Bader"
homepage  = "https://github.com/benjamin-bader"
